# Generated by Django 3.0.6 on 2020-05-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResortName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resort_name_text', models.CharField(max_length=500)),
                ('booking_date', models.DateTimeField(verbose_name='date booked')),
            ],
        ),
        migrations.CreateModel(
            name='ResortReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resort_review_text', models.CharField(max_length=600)),
                ('resortR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resorts.ResortName')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish_name_text', models.CharField(max_length=300)),
                ('resortD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resorts.ResortName')),
            ],
        ),
    ]
